<h3 id="seasons">Seasons, codes</h3>



<table id="04-edtf"><caption>Season codes from <a href="https://www.loc.gov/standards/datetime/">Extended Data/Time Format excerpts</a></caption>
<tr>
	<th>Code</th>
	<th>Meaning</th>
	</tr>

	<tr>
		<td>21</td>
		<td>Spring (independent of location)</td>
		</tr>

	<tr>
		<td>22</td>
		<td>Summer (independent of location)</td>
		</tr>

	<tr>
		<td>23</td>
		<td>Autumn (independent of location)</td>
		</tr>

	<tr>
		<td>24</td>
		<td>Winter (independent of location)</td>
		</tr>


	<tr>
		<td>25</td>
		<td>Spring - Northern Hemisphere</td>
		</tr>

	<tr>
		<td>26</td>
		<td>Summer - Northern Hemisphere</td>
		</tr>

	<tr>
		<td>27</td>
		<td>Autumn - Northern Hemisphere</td>
		</tr>

	<tr>
		<td>28</td>
		<td>Winter - Northern Hemisphere</td>
		</tr>

	<tr>
		<td>29</td>
		<td>Spring - Southern Hemisphere</td>
		</tr>

	<tr>
		<td>30</td>
		<td>Summer - Southern Hemisphere</td>
		</tr>

	<tr>
		<td>31</td>
		<td>Autumn - Southern Hemisphere</td>
		</tr>

	<tr>
		<td>32</td>
		<td>Winter - Southern Hemisphere</td>
		</tr>

<!--
	<tr>
		<td>
		</td>
		<td>
		</td>
		</tr>

-->

</table>
