#!/bin/sh
#Assemble index.html, much of which is concatenating files

main() {

	ofile='./index.html'

	#remove old output file, if present
		if [ -f $ofile ]; then
			rm $ofile
			fi

	printf '<!DOCTYPE html>' >> "$ofile"
	printf '\n<html lang="en">' >> "$ofile"
	printf '\n<head>' >> "$ofile"
	printf '\n<meta name="viewport" content="width=device-width, initial-scale=1">' >> "$ofile"
	printf '\n<title>Heat, Ventillation, A/C (hvac)</title>' >> "$ofile"
	printf '\n\n' >> $ofile
	addCss $ofile
	printf '\n\n' >> $ofile
	printf '\n</head><body>' >> "$ofile"
	addHtml $ofile

	#printf '\n\n' >> $ofile
	#addTables

	printf '\n\n' >> $ofile
	addJs $ofile

	#moving module/script to end of body enabled it to work for custom element. Didn't work at top of file.
	printf '\n\n' >> $ofile
	printf '\n<script type="module" src="./imports.js"></script>' >> "$ofile" #lists imported modules

	printf '\n\n</body></html>' >> "$ofile"


}

addCss() {
	pfx='css/'
	printf '\n\n' >> $1
	cat ${pfx}element.css >> $1
	#cat ${pfx}style1.css >> $1
}

addHtml() {
	pfx='html/'
	cat ${pfx}01-frontNew >> $1 #new file with custom element		
	#cat ${pfx}'02-frontPrev' >> $1  #front end and buttons when tables of data loaded
}

addTables() {
	#Add html tables - tables contain data, first version of software
	printf '\n\n<br><hr><br>\n\n' >> $1
	pfx='dataTables/'
	cat ${pfx}'03-ofc1' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'04-ofc2' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'05-rm1' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'06-rm4' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'07-nursery' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'08-wc' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'09-modA' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'10-modB' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
	cat ${pfx}'11-modC' >> $1
	printf '\n\n<br><hr><br>\n\n' >> $1
}

addJs() {
	#javascript files
	pfx='js/'
	printf '\n\n' >> $1
	printf '\n<script>' >> $1
	printf '\n\n' >> $1

	cat ${pfx}99-test.js	>> $1  #test the import, resolve reference error

	#printf '\n\n' >> $1
	#cat ${pfx}13-globals.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}14-listeners.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}17-readTables.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}15-select1.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}16-rpt.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}19-mkJsonFile.js >> $1
	#printf '\n\n' >> $1
	#cat ${pfx}20-copyClipboard.js	>> $1
	#printf '\n\n' >> $1
	printf '\n</script>' >> $1
}

main "$@"; exit 0

#Old code waiting before delete
#	case "$1" in
#		"m") #manual concatenante		
#			printf '\nnot implemented'
#			;;
#		"ac") #automated concatenate
#			printf '\noption ac deactivated due to not knowing how to operate find -regex'
#
#			#decided to hardcode instead of using gnu find due to delay getting the correct regex
#				#files==$(find . -type f -regex '\./[0-9][0-9].*') #output with =
#				#files=$(find . -regextype posix-basic -regex '\./.[[:digit:]]*') #no output
#				#files==$(find . -type f -regex '^\d\d.*') #no output
#				#files==$(find . -type f -regex  '\d{2}.*') #no output
#				#files==$(find . -type f -regex  '([1-9]|1[0-2])-.*') #no output
#				#files==$(find . -type f -regex  '0[0-2]-.*') #no output
#			#printf '\ndebug files=%s' $files
#
#			#subsort=$(printf '%s' "$files" | sort)
#			#for i in $subsort; do
#			#	printf '\ndebug files again%s' $i
#			#	#printf '\n\n' >> "$i"
#			#	#cat "$i" >> "$ofile"
#			#done
#			;;
#		*)
#			printf '\nunexpected choice / case %s. Expected ./0 c    ..... exiting' "$choice"; exit 1
#		;;
#	esac
