#!/bin/sh
#Check json files for error(s)

main() {
	case "$1" in
		"1")
			file='globals/table.defaults-nest.json'
			#file='office1/table.programs.json'
			#file='globals/subyearGroupings.json'
			verify1JsonFile $file
			;;
		"vd") #verify a range ofjson files
			files=$(find . -maxdepth 1 -name "*.json")
			#printf '\nl0 debug, json files found = %s' "$files"
			for f in $files; do
				#printf '\ndebug looping for file %s' $f
				verify1JsonFile $f
				done #end for

			#json_string=$(cat ofc1.json)
			#if jq -e . >/dev/null 2>&1 <<<"$json_string"; then
			#	echo "Parsed JSON successfully and got something other than false/null"
			#else
			#	echo "Failed to parse JSON, or got false/null"
			#fi
			;;
		"t") #have jq report line number of an error
			file=programs/table.office1.json
			cat "$file" | jq
			;;
		"o")
			printf '\nWhen coded, this was a previous way to check a json file'
			#debug json errors
			#	printf 'debugging JSON file'
			#	file=tmp.json
			#	cat "$file" | jq
			#exit 0
			;;
		*)
			printf '\nunexpected choice / case %s, exiting' "$1"; exit 1
		;;
	esac
} #end function


verify1JsonFile() {
	printf '\nchecking file %s\n' "$1"
	if jq empty $1; then
		printf '\njson is valid for %s' $1
	else
		printf 'json INVALID for %s' $1
	fi
}

main "$@"; exit 0
